### ISSUE TITLE
Review Apps

### ISSUE THREAD

**Issue by zupo** [niteoweb/salarycalc#17]
I want to be able to quickly try different positions/cities/ratios in salary calc, so that I can simulate different scenarios, without needing to clone the code locally, compiling elm, running the dev server, etc.

Create a system similar to [Review Apps on Heroku](https://blog.niteo.co/staging-like-its-2019/) that deploys the Salary Calc for every PR, with changes applied.

First idea that comes to mind is netlify.

**Comment by lzrski** [comment]
I guess we can close it now that #21 is merged.
