### ISSUE TITLE
Configure positions and roles in a JSON file

### ISSUE THREAD

**Issue by zupo** [niteoweb/salarycalc#25]
Modify salarycalc so that all positions and cities are read from a JSON file. Then, since we now have "review apps" style of PR previes, anyone can change the JSON file directly in GitHub, submit a PR and use the modified salary calc that is linked in the PR.

**Comment by lzrski** [comment]
I suppose it would also be nice to pass this JSON data to the app on `init`. That way it would be more useful for non-niteo users. They wouldn't have to fork the project, just install it and use like this:

```js
SalaryCalculator.init(domNode, { cities: {}, roles: {} })
```

Basically the flags pattern.
