### ISSUE TITLE
Information Technology Director should not be in the calc

### ISSUE THREAD

**Issue by dmurko** [niteoweb/salarycalc#46]
https://niteo.co/salary-calculator

<img width="594" alt="Screenshot 2020-05-04 at 09 49 17" src="https://user-images.githubusercontent.com/1309671/80945665-97650600-8dec-11ea-8f44-b42c2289bda9.png">

**Comment by zupo** [comment]
Why?

**Comment by dmurko** [comment]
We said we don't put our salaries in the calc, and that's now only for us. It's also not defined in the Handbook.
